// loading
export const LOADING_TOGGLE = 'LOADING_TOGGLE';

// vocabulary
export const VOCABULARY_ADD = 'VOCABULARY_ADD';
export const VOCABULARY_REMOVE = 'VOCABULARY_REMOVE';
export const VOCABULARY_RENAME = 'VOCABULARY_RENAME';
export const VOCABULARY_EDIT_WORDS = 'VOCABULARY_EDIT_WORDS';
export const VOCABULARIES_GET = 'VOCABULARIES_GET';

// translations
export const TRANSLATIONS_GET = 'TRANSLATIONS_GET';
export const TRANSLATIONS_CLEAR = 'TRANSLATIONS_CLEAR';
